### ISSUE TITLE
FastTensorDataLoader shuffles the indices and not the actual data tensors 

### ISSUE THREAD

**Issue by Alfred-N** [YinengWang/Supervised-Image-Classification-with-Noisy-Labels-Using-Deep-Learning#12]
I think the shuffling is bugged still. I think the code only shuffles the indices and not the actual data tensors.
```

def __iter__(self):
        if self.shuffle:
            self.indices = torch.randperm(self.dataset_len)
        else:
            self.indices = None
        self.i = 0
        return self
```
Am I missing something or is this the case?

**Comment by rlindsberg** [comment]
https://github.com/YinengWang/Supervised-Image-Classification-with-Noisy-Labels-Using-Deep-Learning/blob/0e69f39000cbcb331c5196c7a5a4bc15ad880925/datasets.py#L43-L49

**Comment by YinengWang** [comment]
There's no problem with the implementation. To see this, notice that to loop through all batches, the `FastDataLoader` does two things:
1. Call `__iter__` right before the loop starts, and initialize indices such that it's shuffled
2. Call `__next__` whenever a batch of data is retrieved

https://github.com/YinengWang/Supervised-Image-Classification-with-Noisy-Labels-Using-Deep-Learning/blob/0e69f39000cbcb331c5196c7a5a4bc15ad880925/datasets.py#L43-L60

And the real retrieval happens when the original tensor is accessed by `indices`:
https://github.com/YinengWang/Supervised-Image-Classification-with-Noisy-Labels-Using-Deep-Learning/blob/0e69f39000cbcb331c5196c7a5a4bc15ad880925/datasets.py#L56

This is (implicitly) verified by the [test case](https://github.com/YinengWang/Supervised-Image-Classification-with-Noisy-Labels-Using-Deep-Learning/blob/0e69f39000cbcb331c5196c7a5a4bc15ad880925/tests/test_noise_generator.py)

**Comment by Alfred-N** [comment]
Ah, I see, yes I noticed shortly after I made the issue. Great that you the test case!

**Comment by rlindsberg** [comment]
I think Yineng is too excited about closing this issue. We let the issue opener close the issue next time!
